<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright" style="background-color: rgba(0,0,0,0);padding: 0;">
	<div style="width:auto;padding-bottom:2%;padding-top:2%;padding-left:8%;background-color: white;font-family:'Oswald',sans-serif !important;">
	    <div class="copy_option" style="background-position:1px;margin-left:1%;padding-left:15px;background-image:url('http://localhost/himani/magento/pub/media/wysiwyg/globe.png');background-size: 10px 10px;background-repeat:no-repeat;float:left;display:inline-block;float:left;">
	    	<select style="border:none;font-size:0.8vw;width:auto;font-family:'Oswald',sans-serif !important;font-weight:bold;">
	    	<option style="font-family:'Oswald',sans-serif !important;font-size:1vw;font-weight:bold;">&emsp;<b>CAD - DOLLAR CANADIEN</b></option>
	    	<option  style="font-family:'Oswald',sans-serif !important;font-size:1vw;font-weight:bold;"><b>EURO</b></option></select>
	    </div>
	    <div class="copy_menu" style="float:left;display:inline-block;width:35%;text-align:center;padding-top:1%;padding-left:15%;">
	    <a href="#" style="padding-top:1%;font-size:0.8vw;"><b>PRIVACY POLICY</b></a>&emsp;&emsp;<a href="#" style="padding-top:1%;font-size:0.8vw;"><b>TERMS AND CONDITIONS</b></a>&emsp;&emsp;<a href="#" style="padding-top:1%;font-size:0.8vw;"><b>SITE MAP</b></a>
	    </div>
	    <div class="copyy_right" style="float:left;display:inline-block;width:30%;font-family:'Oswald',sans-serif !important;font-size:0.8vw;padding-top:1%;color:black;text-align:right;">
	   <?php /* @escapeNotVerified */ echo $block->getCopyright() ?>
	   	
	</div>
    
</small>
